import '../../blocks/dropdown/dropdown-init';
import '../../blocks/slick/slick-init';
import '../../blocks/range-slider/range-slider';
import '../../blocks/pagination/pagination-init';
import '../../blocks/checkbox-list/checkbox-list';
import '../../scss/main.scss';
import './room-search.scss';
import '../../blocks/burger/burger-init';
import '../../blocks/calendar/calendar-init';
